# Generated by Django 3.1 on 2020-08-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_auto_20200827_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meds',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
