# Generated by Django 3.1 on 2020-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_auto_20200829_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='actioned',
            field=models.BooleanField(default=False),
        ),
    ]
