# Generated by Django 3.1 on 2020-08-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_meds_actioned'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
