# Generated by Django 3.1 on 2020-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField(max_length=30)),
                ('medicine_name', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=30)),
                ('password2', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address1', models.TextField(default='', max_length=30)),
                ('address2', models.TextField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('postcode', models.CharField(default='', max_length=30)),
                ('username', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
