# Generated by Django 3.1 on 2020-08-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('medical_num', models.CharField(max_length=8)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
            ],
        ),
    ]
