# Generated by Django 3.1 on 2020-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(default='email', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='password1',
            field=models.CharField(default='password1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='password2',
            field=models.CharField(default='password2', max_length=15),
            preserve_default=False,
        ),
    ]
